add_test( [==[Board contracts]==] /home/ludvig/programs/Group-9-backend-libSMCE/test/SMCE_Tests [==[Board contracts]==]  )
set_tests_properties( [==[Board contracts]==] PROPERTIES WORKING_DIRECTORY /home/ludvig/programs/Group-9-backend-libSMCE/test)
add_test( [==[Board exit_notify]==] /home/ludvig/programs/Group-9-backend-libSMCE/test/SMCE_Tests [==[Board exit_notify]==]  )
set_tests_properties( [==[Board exit_notify]==] PROPERTIES WORKING_DIRECTORY /home/ludvig/programs/Group-9-backend-libSMCE/test)
add_test( [==[Mixed INO/C++ sources]==] /home/ludvig/programs/Group-9-backend-libSMCE/test/SMCE_Tests [==[Mixed INO/C++ sources]==]  )
set_tests_properties( [==[Mixed INO/C++ sources]==] PROPERTIES WORKING_DIRECTORY /home/ludvig/programs/Group-9-backend-libSMCE/test)
add_test( [==[BoardView GPIO]==] /home/ludvig/programs/Group-9-backend-libSMCE/test/SMCE_Tests [==[BoardView GPIO]==]  )
set_tests_properties( [==[BoardView GPIO]==] PROPERTIES WORKING_DIRECTORY /home/ludvig/programs/Group-9-backend-libSMCE/test)
add_test( [==[BoardView UART]==] /home/ludvig/programs/Group-9-backend-libSMCE/test/SMCE_Tests [==[BoardView UART]==]  )
set_tests_properties( [==[BoardView UART]==] PROPERTIES WORKING_DIRECTORY /home/ludvig/programs/Group-9-backend-libSMCE/test)
add_test( [==[BoardView RGB444 cvt]==] /home/ludvig/programs/Group-9-backend-libSMCE/test/SMCE_Tests [==[BoardView RGB444 cvt]==]  )
set_tests_properties( [==[BoardView RGB444 cvt]==] PROPERTIES WORKING_DIRECTORY /home/ludvig/programs/Group-9-backend-libSMCE/test)
add_test( [==[BoardView RGB565 cvt]==] /home/ludvig/programs/Group-9-backend-libSMCE/test/SMCE_Tests [==[BoardView RGB565 cvt]==]  )
set_tests_properties( [==[BoardView RGB565 cvt]==] PROPERTIES WORKING_DIRECTORY /home/ludvig/programs/Group-9-backend-libSMCE/test)
add_test( [==[Basic board device]==] /home/ludvig/programs/Group-9-backend-libSMCE/test/SMCE_Tests [==[Basic board device]==]  )
set_tests_properties( [==[Basic board device]==] PROPERTIES WORKING_DIRECTORY /home/ludvig/programs/Group-9-backend-libSMCE/test)
add_test( [==[Invalid manifests processing]==] /home/ludvig/programs/Group-9-backend-libSMCE/test/SMCE_Tests [==[Invalid manifests processing]==]  )
set_tests_properties( [==[Invalid manifests processing]==] PROPERTIES WORKING_DIRECTORY /home/ludvig/programs/Group-9-backend-libSMCE/test)
add_test( [==[Valid manifests processing]==] /home/ludvig/programs/Group-9-backend-libSMCE/test/SMCE_Tests [==[Valid manifests processing]==]  )
set_tests_properties( [==[Valid manifests processing]==] PROPERTIES WORKING_DIRECTORY /home/ludvig/programs/Group-9-backend-libSMCE/test)
add_test( [==[Board remote preproc lib]==] /home/ludvig/programs/Group-9-backend-libSMCE/test/SMCE_Tests [==[Board remote preproc lib]==]  )
set_tests_properties( [==[Board remote preproc lib]==] PROPERTIES WORKING_DIRECTORY /home/ludvig/programs/Group-9-backend-libSMCE/test)
add_test( [==[Patch lib]==] /home/ludvig/programs/Group-9-backend-libSMCE/test/SMCE_Tests [==[Patch lib]==]  )
set_tests_properties( [==[Patch lib]==] PROPERTIES WORKING_DIRECTORY /home/ludvig/programs/Group-9-backend-libSMCE/test)
add_test( [==[WiFi intended use]==] /home/ludvig/programs/Group-9-backend-libSMCE/test/SMCE_Tests [==[WiFi intended use]==]  )
set_tests_properties( [==[WiFi intended use]==] PROPERTIES WORKING_DIRECTORY /home/ludvig/programs/Group-9-backend-libSMCE/test)
add_test( [==[SD polyfill]==] /home/ludvig/programs/Group-9-backend-libSMCE/test/SMCE_Tests [==[SD polyfill]==]  )
set_tests_properties( [==[SD polyfill]==] PROPERTIES WORKING_DIRECTORY /home/ludvig/programs/Group-9-backend-libSMCE/test)
add_test( [==[Toolchain invalid]==] /home/ludvig/programs/Group-9-backend-libSMCE/test/SMCE_Tests [==[Toolchain invalid]==]  )
set_tests_properties( [==[Toolchain invalid]==] PROPERTIES WORKING_DIRECTORY /home/ludvig/programs/Group-9-backend-libSMCE/test)
add_test( [==[Toolchain valid]==] /home/ludvig/programs/Group-9-backend-libSMCE/test/SMCE_Tests [==[Toolchain valid]==]  )
set_tests_properties( [==[Toolchain valid]==] PROPERTIES WORKING_DIRECTORY /home/ludvig/programs/Group-9-backend-libSMCE/test)
set( SMCE_Tests_TESTS [==[Board contracts]==] [==[Board exit_notify]==] [==[Mixed INO/C++ sources]==] [==[BoardView GPIO]==] [==[BoardView UART]==] [==[BoardView RGB444 cvt]==] [==[BoardView RGB565 cvt]==] [==[Basic board device]==] [==[Invalid manifests processing]==] [==[Valid manifests processing]==] [==[Board remote preproc lib]==] [==[Patch lib]==] [==[WiFi intended use]==] [==[SD polyfill]==] [==[Toolchain invalid]==] [==[Toolchain valid]==])
